### ISSUE TITLE
Gender_fixed and DOB_fixed columns mixed up

### ISSUE THREAD

**Issue by Treviisolion** [Conraw/KrucialStaffing#10]
Comparing the Gender_fixed and DOB_fixed columns of PostFormatting-Comparison.csv and the Gender OK? and DOB OK? columns of POSTcomparison.csv, noticed that the values of Gender_fixed where showing up in the DOB OK? column and vice versa.

**Comment by Conraw** [comment]
this has been corrected. Good catch, this probably also resolves #9
