### ISSUE TITLE
Missing Comparisons

### ISSUE THREAD

**Issue by Treviisolion** [Conraw/KrucialStaffing#11]
Initial Blue columns do not have comparisons being done

**Comment by Treviisolion** [comment]
As a bit of prelimary to this, I am working on getting the Workday ID from AM to be kept through our process so it can be compared to the others. Got to Workday into Master file. Also pushing DOB from AM through as well.

**Comment by Conraw** [comment]
AM export did not have dob

**Comment by Treviisolion** [comment]
All comparisons should be being done now.
