### ISSUE TITLE
Phone Number Comparison Broken

### ISSUE THREAD

**Issue by Treviisolion** [Conraw/KrucialStaffing#22]
It broke again

**Comment by Conraw** [comment]
its being treated as a float when it gets read into master comparsion. only that one is though even though all of them should be considered numbers.

**Comment by Conraw** [comment]
dfMaster['Phone_WD'] = dfMaster['Phone_WD'].str[:10] doing this makes Mobilize also a float.

better solution might be appending in a row at the end that will force everything to be an object

**Comment by Treviisolion** [comment]
Alternatively we can force it to read all the phone numbers as strings and that fixes it. Can't force the whole file however because Mobilize id numbers in Alert Media are still formatting automatically to floats but it works because it can apparently compare integers to floats and work, so long as they are numbers and not their string versions. Though I think I'm just going to do some stuff to take care of that.

**Comment by Treviisolion** [comment]
Ok this issue is resolved at least.
