### ISSUE TITLE
Look into more merges

### ISSUE THREAD

**Issue by Conraw** [Conraw/KrucialStaffing#25]
Merge of formatted phone/concat names etc

**Comment by Conraw** [comment]
probably left merge on email, left merge on phone then append those two together and drop dubs

**Comment by Treviisolion** [comment]
Could also try merging on profile ids where that info is available

**Comment by Treviisolion** [comment]
Merging on Email, Phone Number, and IDs. For some reason Workday produces a bunch of duplicates before they are dropped.
