### ISSUE TITLE
Alert media city to state swap

### ISSUE THREAD

**Issue by Conraw** [Conraw/KrucialStaffing#32]
Add in code where if the city in Alert media is a state. and it correct in the other X amount of sources, it gets added into the bulk alert media update.

**Comment by Conraw** [comment]
into alert media bulk update

**Comment by Treviisolion** [comment]
Just quickly did this, still checking to make certain we have 2 sources of information and that all the sources we have match, so noticed there are still a few that are not getting updated, but most should be caught. If we only care about them matching, you can remove the (BEE | WDE) portion from line 42.
