### ISSUE TITLE
stripping zip code of the extension

### ISSUE THREAD

**Issue by Conraw** [Conraw/KrucialStaffing#8]

**Comment by Conraw** [comment]
needs to be thought on more, should the sources have the extension removed since it provides almost no info as a decent amount are just -0000. 

Also, for address city state zip comparsion only compares 3 sources. however there are 4 that have this information?

**Comment by Treviisolion** [comment]
After discussing it with Connor, it was determined that we did not want to remove the -0000 as we want that gone from the original source. Found workday was missing from comparison, has been added.
