### ISSUE TITLE
DOB_incorrect

### ISSUE THREAD

**Issue by Treviisolion** [Conraw/KrucialStaffing#9]
19311 comparisons for Date of Birth that are not correct. Says fix when should be correct. All those that should be fixed do say fix, and those that say correct are correct, but some that say fix should be correct.

**Comment by Conraw** [comment]
should be fixed with the issue solution on #10

**Comment by Treviisolion** [comment]
It's mostly fine now. There were a bunch of entries that were not formatting correctly when they had single digit dates or months, so forced a reformat. There are still 127 oddities, but I don't know what's going on with them as they all for whatever reason show up as normal dates in Excel, but in pandas are just odd. Row 2857 is an example. However it is possible that they are problems in the sources themselves so I'm considering this fixed.
